LIB_NAME=libcrates.so
PLUGIN_NAME=crates.so
LUA_DIR =/home/willothy/projects/neovim/sidebar-crates/lua
DEPS_DIR=/home/willothy/projects/neovim/sidebar-crates/lua/deps

TARGET_DIR=/home/willothy/projects/neovim/sidebar-crates/target/release

.PHONY: deploy
deploy:
	cp ${TARGET_DIR}/${LIB_NAME} ${LUA_DIR}/${PLUGIN_NAME}
	cp ${TARGET_DIR}/deps/*.rlib ${DEPS_DIR}
